// A verifiable source the brief can cite inline as [S#]. The route owns this
// list (built from the supplied events), so the model cannot fabricate a source.
export interface BriefSource {
  tag: string        // e.g. "S1" — matches the [S1] markers used inline in the prose
  title: string
  source?: string    // outlet / origin
  url?: string
  date?: string      // ISO or display date
}

// An IC-style key judgment: a discrete analytic conclusion carrying its own
// confidence, the reasoning behind it, and the source tags that support it.
export interface BriefKeyJudgment {
  judgment: string
  confidence: 'HIGH' | 'MODERATE' | 'LOW'
  reasoning?: string
  citations?: string[]   // source tags, e.g. ["S2", "S5"]
}

// Analysis of Competing Hypotheses entry — the structured "what could be true"
// that keeps the assessment honest and falsifiable.
export interface BriefHypothesis {
  hypothesis: string
  likelihood: string    // IC probability language, e.g. "likely (70-95%)"
  assessment: string    // why the evidence supports / undercuts it
  citations?: string[]
}

// Country brief — generated by /api/brief. Structured as a publishable-grade
// analytic product: every legacy field is preserved for backward compatibility,
// the academic fields below are additive and optional.
export interface CountryBriefData {
  executiveSummary: string
  situationAssessment: string
  keyActors: { name: string; role: string; assessment: string }[]
  riskFactors: { factor: string; severity: string; detail: string }[]
  economicExposure: string
  outlook30: string
  outlook90: string
  watchItems: string[]
  confidenceLevel: string
  maritimeAviationPicture?: string | null
  analystNotes?: string | null
  // Academic / publishable layer (additive — older saved briefs omit these)
  keyJudgments?: BriefKeyJudgment[]
  competingHypotheses?: BriefHypothesis[]
  assumptions?: string[]
  intelligenceGaps?: string[]
  methodology?: string | null
  sources?: BriefSource[]   // injected by the route from its source map (verifiable references)
}

// Deterministic generation record — built by the route from what ACTUALLY went
// into the brief, never model-written. This is the client-defensible
// "how this was made" appendix for exported deliverables.
export interface BriefGenerationMeta {
  generatedAt: string
  provider: string
  model: string
  effort: string
  /** Events supplied by the workspace. */
  eventCount: number
  /** Events actually tagged [E#] in the corpus the model read. */
  citedCorpusSize: number
  /** Cited events carrying full article text (not just metadata). */
  fullTextDocs: number
  /** Share (0-1) of cited events with NATO A/B source reliability. */
  gradedShare: number
  trackedActorCount: number
  /** Curated [J#] journal entries included. */
  curatedEntries: number
}

// Project brief — generated by /api/brief/project (API; export panel uses client-side PDF)
export interface ProjectBriefData {
  classification: string
  bluf: string
  situation: string
  keyFindings: { finding: string; significance: string; confidence: 'HIGH' | 'MEDIUM' | 'LOW' }[]
  patterns: string
  outlook: string
  analystNote: string
  tags: string[]
  // Academic / publishable layer (additive — older saved briefs omit these)
  competingHypotheses?: BriefHypothesis[]
  assumptions?: string[]
  intelligenceGaps?: string[]
  methodology?: string | null
  sources?: BriefSource[]   // injected by the route from its [E#] source map (verifiable references)
  /** Deterministic generation record injected by the route — never model-written */
  generation?: BriefGenerationMeta
}

// Union stored in the briefs table — either shape is valid
export type AnyBriefData = CountryBriefData | ProjectBriefData

/** Human-readable methodology appendix lines from the generation record. Pure. */
export function briefMethodologyLines(g: BriefGenerationMeta): string[] {
  const graded = Math.round(g.gradedShare * 100)
  const lines = [
    `Generated ${g.generatedAt.slice(0, 16).replace('T', ' ')} UTC by ${g.provider} (${g.model}, effort: ${g.effort}).`,
    `Evidence base: ${g.citedCorpusSize} cited events selected from a ${g.eventCount}-event workspace corpus; ${g.fullTextDocs} carried full source text; ${graded}% of cited events have NATO A/B-grade sources.`,
  ]
  const inputs: string[] = []
  if (g.trackedActorCount > 0) inputs.push(`${g.trackedActorCount} tracked actor dossier${g.trackedActorCount !== 1 ? 's' : ''} (deterministic, [E#]-anchored)`)
  if (g.curatedEntries > 0) inputs.push(`${g.curatedEntries} analyst-curated journal entr${g.curatedEntries !== 1 ? 'ies' : 'y'} ([J#])`)
  if (inputs.length) lines.push(`Analyst inputs: ${inputs.join('; ')}.`)
  lines.push('Technique: ACH seed hypotheses scored against cited evidence; all inline [E#]/[J#] tags resolve to the source list — uncited claims should be treated as unsupported.')
  return lines
}
