import { briefMethodologyLines, type ProjectBriefData } from '@/types/brief'

export function projectBriefToMarkdown(
  brief: ProjectBriefData,
  meta: { projectName: string; regionName: string; researchQuestion?: string; generatedAt?: string },
): string {
  const lines: string[] = [
    `# Intelligence Brief — ${meta.projectName}`,
    '',
    `**Region:** ${meta.regionName}`,
    meta.researchQuestion ? `**Research question:** ${meta.researchQuestion}` : '',
    meta.generatedAt ? `**Generated:** ${meta.generatedAt}` : '',
    '',
    `> ${brief.classification}`,
    '',
    '## BLUF',
    brief.bluf,
    '',
    '## Situation',
    brief.situation,
    '',
    '## Key findings',
    ...brief.keyFindings.map(f =>
      `- **${f.finding}** — ${f.significance} *(confidence: ${f.confidence})*`,
    ),
    '',
  ]

  if (brief.competingHypotheses?.length) {
    lines.push('## Analysis of competing hypotheses')
    brief.competingHypotheses.forEach((h, i) => {
      const cites = h.citations?.length ? ` ${h.citations.map(c => `[${c}]`).join('')}` : ''
      lines.push(`- **H${i + 1} — ${h.likelihood}:** ${h.hypothesis}${cites}`)
      if (h.assessment) lines.push(`  - ${h.assessment}`)
    })
    lines.push('')
  }

  if (brief.assumptions?.length) {
    lines.push('## Assumptions', ...brief.assumptions.map(a => `- ${a}`), '')
  }

  lines.push('## Patterns', brief.patterns, '')
  lines.push('## Outlook', brief.outlook, '')

  if (brief.intelligenceGaps?.length) {
    lines.push('## Intelligence gaps', ...brief.intelligenceGaps.map(g => `- ${g}`), '')
  }

  lines.push('## Analyst note', brief.analystNote, '')
  if (brief.methodology) lines.push('## Methodology', brief.methodology, '')
  if (brief.generation) {
    lines.push('## How this brief was made', ...briefMethodologyLines(brief.generation).map(l => `- ${l}`), '')
  }

  if (brief.sources?.length) {
    lines.push('## Sources')
    brief.sources.forEach(s => {
      const meta = [s.source, s.date].filter(Boolean).join(', ')
      const link = s.url ? `[${s.title}](${s.url})` : s.title
      lines.push(`- **[${s.tag}]** ${link}${meta ? ` — ${meta}` : ''}`)
    })
    lines.push('')
  }

  lines.push(
    brief.tags?.length ? `**Tags:** ${brief.tags.join(', ')}` : '',
    '',
    '---',
    '*Generated by ARGUS*',
  )
  return lines.filter(l => l !== undefined).join('\n')
}
