import type { CountryBriefData, ProjectBriefData } from '@/types/brief'
import type { CanvasBriefResponse } from '@/types/canvasBrief'
import { countryBriefToMarkdown } from '@/lib/countryBriefClient'
import { projectBriefToMarkdown } from '@/lib/briefMarkdown'

export type BriefHistoryType = 'country' | 'project' | 'canvas'

export interface BriefHistoryRecord {
  id: string
  type: BriefHistoryType
  title: string
  country: string
  country_code: string
  project_id: string | null
  data: Record<string, unknown> | null
  summary: string
  created_at: string
}

export function briefSummary(type: BriefHistoryType, brief: Record<string, unknown>): string {
  if (type === 'country') {
    const b = brief as unknown as CountryBriefData
    return (b.executiveSummary || '').slice(0, 300)
  }
  if (type === 'project') {
    const b = brief as unknown as ProjectBriefData
    return (b.bluf || '').slice(0, 300)
  }
  const b = brief as unknown as CanvasBriefResponse
  return (b.headline || b.situation || '').slice(0, 300)
}

export function briefToMarkdown(record: BriefHistoryRecord): string {
  const data = record.data ?? {}
  const generatedAt = new Date(record.created_at).toLocaleString('en-US', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })

  if (record.type === 'country') {
    return countryBriefToMarkdown(data as unknown as CountryBriefData, record.country || record.title)
  }
  if (record.type === 'project') {
    return projectBriefToMarkdown(data as unknown as ProjectBriefData, {
      projectName: record.title.replace(/ intelligence brief$/i, ''),
      regionName: record.country || '',
      generatedAt,
    })
  }

  const b = data as unknown as CanvasBriefResponse
  return [
    `# Canvas Assessment — ${record.title}`,
    '',
    `**Generated:** ${generatedAt}`,
    '',
    '## Headline',
    b.headline,
    '',
    '## Situation',
    b.situation,
    '',
    '## Key findings',
    ...(b.keyFindings ?? []).map(f => `- ${f}`),
    '',
    `**Risk:** ${b.riskLevel} — ${b.riskRationale}`,
    '',
    '## Assessment',
    b.assessmentInsight,
    '',
    '## Watch items',
    ...(b.watchItems ?? []).map(w => `- ${w}`),
    '',
    '## Analyst judgment',
    b.analystJudgment,
    '',
    `**Confidence:** ${b.confidence} — ${b.confidenceRationale}`,
    '',
    '---',
    '*Generated by ARGUS*',
  ].join('\n')
}

export const BRIEF_TYPE_LABEL: Record<BriefHistoryType, string> = {
  country: 'Country',
  project: 'Project',
  canvas: 'Canvas',
}
