export const KNOWN_LOCATIONS: Record<string, { lat: number; lng: number; country: string; region: string }> = {
  // ── Afghanistan ──────────────────────────────────────────────────────────
  kabul: { lat: 34.52, lng: 69.17, country: 'AF', region: 'Central Asia' },
  kandahar: { lat: 31.61, lng: 65.71, country: 'AF', region: 'Central Asia' },
  herat: { lat: 34.35, lng: 62.20, country: 'AF', region: 'Central Asia' },
  jalalabad: { lat: 34.43, lng: 70.45, country: 'AF', region: 'Central Asia' },
  mazar: { lat: 36.71, lng: 67.11, country: 'AF', region: 'Central Asia' },
  'mazar-i-sharif': { lat: 36.71, lng: 67.11, country: 'AF', region: 'Central Asia' },
  kunduz: { lat: 36.72, lng: 68.87, country: 'AF', region: 'Central Asia' },

  // ── Pakistan ─────────────────────────────────────────────────────────────
  islamabad: { lat: 33.72, lng: 73.06, country: 'PK', region: 'South Asia' },
  karachi: { lat: 24.86, lng: 67.01, country: 'PK', region: 'South Asia' },
  lahore: { lat: 31.55, lng: 74.34, country: 'PK', region: 'South Asia' },
  peshawar: { lat: 34.01, lng: 71.57, country: 'PK', region: 'South Asia' },
  quetta: { lat: 30.19, lng: 67.01, country: 'PK', region: 'South Asia' },
  rawalpindi: { lat: 33.60, lng: 73.04, country: 'PK', region: 'South Asia' },
  multan: { lat: 30.20, lng: 71.47, country: 'PK', region: 'South Asia' },

  // ── India ─────────────────────────────────────────────────────────────────
  'new delhi': { lat: 28.61, lng: 77.21, country: 'IN', region: 'South Asia' },
  delhi: { lat: 28.61, lng: 77.21, country: 'IN', region: 'South Asia' },
  mumbai: { lat: 19.08, lng: 72.88, country: 'IN', region: 'South Asia' },
  kolkata: { lat: 22.57, lng: 88.36, country: 'IN', region: 'South Asia' },
  chennai: { lat: 13.08, lng: 80.27, country: 'IN', region: 'South Asia' },
  bangalore: { lat: 12.97, lng: 77.59, country: 'IN', region: 'South Asia' },
  bengaluru: { lat: 12.97, lng: 77.59, country: 'IN', region: 'South Asia' },
  hyderabad: { lat: 17.38, lng: 78.49, country: 'IN', region: 'South Asia' },
  lucknow: { lat: 26.85, lng: 80.95, country: 'IN', region: 'South Asia' },
  srinagar: { lat: 34.08, lng: 74.80, country: 'IN', region: 'South Asia' },
  amritsar: { lat: 31.63, lng: 74.87, country: 'IN', region: 'South Asia' },
  ahmedabad: { lat: 23.02, lng: 72.57, country: 'IN', region: 'South Asia' },
  'jammu and kashmir': { lat: 34.08, lng: 74.80, country: 'IN', region: 'South Asia' },
  manipur: { lat: 24.66, lng: 93.91, country: 'IN', region: 'South Asia' },
  imphal: { lat: 24.81, lng: 93.94, country: 'IN', region: 'South Asia' },
  arunachal: { lat: 27.09, lng: 93.61, country: 'IN', region: 'South Asia' },
  // Ladakh / LAC flashpoints
  ladakh: { lat: 34.23, lng: 77.56, country: 'IN', region: 'South Asia' },
  leh: { lat: 34.16, lng: 77.58, country: 'IN', region: 'South Asia' },
  kargil: { lat: 34.56, lng: 76.13, country: 'IN', region: 'South Asia' },
  galwan: { lat: 34.76, lng: 78.14, country: 'IN', region: 'South Asia' },
  'galwan valley': { lat: 34.76, lng: 78.14, country: 'IN', region: 'South Asia' },
  pangong: { lat: 33.76, lng: 78.66, country: 'IN', region: 'South Asia' },
  'pangong tso': { lat: 33.76, lng: 78.66, country: 'IN', region: 'South Asia' },
  demchok: { lat: 32.70, lng: 79.44, country: 'IN', region: 'South Asia' },
  chushul: { lat: 33.58, lng: 78.64, country: 'IN', region: 'South Asia' },
  'depsang': { lat: 35.30, lng: 77.86, country: 'IN', region: 'South Asia' },
  'daulat beg oldi': { lat: 35.40, lng: 77.90, country: 'IN', region: 'South Asia' },
  'hot springs': { lat: 34.33, lng: 78.97, country: 'IN', region: 'South Asia' },
  'gogra': { lat: 34.42, lng: 78.87, country: 'IN', region: 'South Asia' },
  nubra: { lat: 34.69, lng: 77.56, country: 'IN', region: 'South Asia' },
  zanskar: { lat: 33.50, lng: 76.90, country: 'IN', region: 'South Asia' },
  tawang: { lat: 27.59, lng: 91.87, country: 'IN', region: 'South Asia' },
  sikkim: { lat: 27.53, lng: 88.51, country: 'IN', region: 'South Asia' },
  'nathu la': { lat: 27.39, lng: 88.83, country: 'IN', region: 'South Asia' },
  'doklam': { lat: 27.29, lng: 88.94, country: 'BT', region: 'South Asia' },
  aksai: { lat: 35.12, lng: 79.13, country: 'CN', region: 'East Asia' },
  'aksai chin': { lat: 35.12, lng: 79.13, country: 'CN', region: 'East Asia' },
  shaksgam: { lat: 36.20, lng: 76.80, country: 'CN', region: 'East Asia' },
  siachen: { lat: 35.42, lng: 77.11, country: 'IN', region: 'South Asia' },
  drass: { lat: 34.43, lng: 75.75, country: 'IN', region: 'South Asia' },
  batalik: { lat: 34.66, lng: 76.42, country: 'IN', region: 'South Asia' },
  shyok: { lat: 34.98, lng: 77.87, country: 'IN', region: 'South Asia' },

  // ── China ─────────────────────────────────────────────────────────────────
  beijing: { lat: 39.91, lng: 116.39, country: 'CN', region: 'East Asia' },
  shanghai: { lat: 31.23, lng: 121.47, country: 'CN', region: 'East Asia' },
  hong: { lat: 22.32, lng: 114.17, country: 'HK', region: 'East Asia' },
  'hong kong': { lat: 22.32, lng: 114.17, country: 'HK', region: 'East Asia' },
  taipei: { lat: 25.05, lng: 121.57, country: 'TW', region: 'East Asia' },
  taiwan: { lat: 23.70, lng: 121.00, country: 'TW', region: 'East Asia' },
  chengdu: { lat: 30.57, lng: 104.07, country: 'CN', region: 'East Asia' },
  wuhan: { lat: 30.59, lng: 114.31, country: 'CN', region: 'East Asia' },
  xinjiang: { lat: 41.19, lng: 85.15, country: 'CN', region: 'East Asia' },
  tibet: { lat: 29.65, lng: 91.12, country: 'CN', region: 'East Asia' },
  lhasa: { lat: 29.65, lng: 91.12, country: 'CN', region: 'East Asia' },

  // ── Russia ─────────────────────────────────────────────────────────────────
  moscow: { lat: 55.75, lng: 37.62, country: 'RU', region: 'Europe' },
  'st. petersburg': { lat: 59.94, lng: 30.32, country: 'RU', region: 'Europe' },
  'saint petersburg': { lat: 59.94, lng: 30.32, country: 'RU', region: 'Europe' },
  belgorod: { lat: 50.60, lng: 36.59, country: 'RU', region: 'Europe' },
  bryansk: { lat: 53.25, lng: 34.37, country: 'RU', region: 'Europe' },
  smolensk: { lat: 54.78, lng: 32.04, country: 'RU', region: 'Europe' },
  rostov: { lat: 47.22, lng: 39.71, country: 'RU', region: 'Europe' },
  volgograd: { lat: 48.71, lng: 44.51, country: 'RU', region: 'Europe' },

  // ── Ukraine ─────────────────────────────────────────────────────────────────
  kyiv: { lat: 50.45, lng: 30.52, country: 'UA', region: 'Europe' },
  kiev: { lat: 50.45, lng: 30.52, country: 'UA', region: 'Europe' },
  kharkiv: { lat: 49.99, lng: 36.23, country: 'UA', region: 'Europe' },
  odesa: { lat: 46.48, lng: 30.72, country: 'UA', region: 'Europe' },
  odessa: { lat: 46.48, lng: 30.72, country: 'UA', region: 'Europe' },
  lviv: { lat: 49.84, lng: 24.03, country: 'UA', region: 'Europe' },
  dnipro: { lat: 48.46, lng: 35.05, country: 'UA', region: 'Europe' },
  zaporizhzhia: { lat: 47.84, lng: 35.14, country: 'UA', region: 'Europe' },
  kherson: { lat: 46.64, lng: 32.62, country: 'UA', region: 'Europe' },
  mariupol: { lat: 47.10, lng: 37.54, country: 'UA', region: 'Europe' },
  donetsk: { lat: 48.02, lng: 37.82, country: 'UA', region: 'Europe' },
  luhansk: { lat: 48.57, lng: 39.34, country: 'UA', region: 'Europe' },
  bakhmut: { lat: 48.60, lng: 37.99, country: 'UA', region: 'Europe' },
  avdiivka: { lat: 48.14, lng: 37.76, country: 'UA', region: 'Europe' },
  kramatorsk: { lat: 48.73, lng: 37.55, country: 'UA', region: 'Europe' },
  sumy: { lat: 50.91, lng: 34.80, country: 'UA', region: 'Europe' },
  mykolaiv: { lat: 46.97, lng: 32.00, country: 'UA', region: 'Europe' },
  chernihiv: { lat: 51.49, lng: 31.29, country: 'UA', region: 'Europe' },
  zaporizhia: { lat: 47.84, lng: 35.14, country: 'UA', region: 'Europe' },
  kurakhove: { lat: 47.98, lng: 37.27, country: 'UA', region: 'Europe' },

  // ── Middle East ───────────────────────────────────────────────────────────
  tehran: { lat: 35.69, lng: 51.39, country: 'IR', region: 'Middle East' },
  isfahan: { lat: 32.66, lng: 51.68, country: 'IR', region: 'Middle East' },
  shiraz: { lat: 29.59, lng: 52.58, country: 'IR', region: 'Middle East' },
  mashhad: { lat: 36.30, lng: 59.60, country: 'IR', region: 'Middle East' },
  tabriz: { lat: 38.08, lng: 46.30, country: 'IR', region: 'Middle East' },
  baghdad: { lat: 33.34, lng: 44.40, country: 'IQ', region: 'Middle East' },
  basra: { lat: 30.51, lng: 47.81, country: 'IQ', region: 'Middle East' },
  mosul: { lat: 36.34, lng: 43.13, country: 'IQ', region: 'Middle East' },
  erbil: { lat: 36.19, lng: 44.01, country: 'IQ', region: 'Middle East' },
  kurdistan: { lat: 36.19, lng: 44.01, country: 'IQ', region: 'Middle East' },
  fallujah: { lat: 33.35, lng: 43.78, country: 'IQ', region: 'Middle East' },
  ramadi: { lat: 33.42, lng: 43.30, country: 'IQ', region: 'Middle East' },
  kirkuk: { lat: 35.47, lng: 44.39, country: 'IQ', region: 'Middle East' },
  damascus: { lat: 33.51, lng: 36.29, country: 'SY', region: 'Middle East' },
  aleppo: { lat: 36.20, lng: 37.16, country: 'SY', region: 'Middle East' },
  homs: { lat: 34.73, lng: 36.72, country: 'SY', region: 'Middle East' },
  hama: { lat: 35.13, lng: 36.75, country: 'SY', region: 'Middle East' },
  idlib: { lat: 35.93, lng: 36.63, country: 'SY', region: 'Middle East' },
  raqqa: { lat: 35.95, lng: 39.00, country: 'SY', region: 'Middle East' },
  deir: { lat: 35.34, lng: 40.14, country: 'SY', region: 'Middle East' },
  'deir ez-zor': { lat: 35.34, lng: 40.14, country: 'SY', region: 'Middle East' },
  jerusalem: { lat: 31.77, lng: 35.22, country: 'IL', region: 'Middle East' },
  'tel aviv': { lat: 32.06, lng: 34.78, country: 'IL', region: 'Middle East' },
  haifa: { lat: 32.81, lng: 34.99, country: 'IL', region: 'Middle East' },
  gaza: { lat: 31.50, lng: 34.47, country: 'PS', region: 'Middle East' },
  'west bank': { lat: 31.96, lng: 35.30, country: 'PS', region: 'Middle East' },
  ramallah: { lat: 31.90, lng: 35.20, country: 'PS', region: 'Middle East' },
  rafah: { lat: 31.29, lng: 34.25, country: 'PS', region: 'Middle East' },
  jenin: { lat: 32.46, lng: 35.30, country: 'PS', region: 'Middle East' },
  beirut: { lat: 33.89, lng: 35.50, country: 'LB', region: 'Middle East' },
  'south lebanon': { lat: 33.27, lng: 35.35, country: 'LB', region: 'Middle East' },
  amman: { lat: 31.96, lng: 35.95, country: 'JO', region: 'Middle East' },
  riyadh: { lat: 24.69, lng: 46.72, country: 'SA', region: 'Gulf' },
  jeddah: { lat: 21.54, lng: 39.17, country: 'SA', region: 'Gulf' },
  dubai: { lat: 25.20, lng: 55.27, country: 'AE', region: 'Gulf' },
  'abu dhabi': { lat: 24.45, lng: 54.38, country: 'AE', region: 'Gulf' },
  doha: { lat: 25.29, lng: 51.53, country: 'QA', region: 'Gulf' },
  muscat: { lat: 23.61, lng: 58.59, country: 'OM', region: 'Gulf' },
  kuwait: { lat: 29.37, lng: 47.98, country: 'KW', region: 'Gulf' },
  manama: { lat: 26.22, lng: 50.59, country: 'BH', region: 'Gulf' },
  sanaa: { lat: 15.35, lng: 44.21, country: 'YE', region: 'Middle East' },
  aden: { lat: 12.78, lng: 45.03, country: 'YE', region: 'Middle East' },
  hudaydah: { lat: 14.80, lng: 42.95, country: 'YE', region: 'Middle East' },
  ankara: { lat: 39.92, lng: 32.85, country: 'TR', region: 'Europe' },
  istanbul: { lat: 41.01, lng: 28.95, country: 'TR', region: 'Europe' },
  cairo: { lat: 30.06, lng: 31.25, country: 'EG', region: 'Middle East' },
  sinai: { lat: 30.50, lng: 33.90, country: 'EG', region: 'Middle East' },

  // ── Africa ────────────────────────────────────────────────────────────────
  khartoum: { lat: 15.55, lng: 32.53, country: 'SD', region: 'Africa' },
  'port sudan': { lat: 19.62, lng: 37.22, country: 'SD', region: 'Africa' },
  darfur: { lat: 13.50, lng: 24.00, country: 'SD', region: 'Africa' },
  'el fasher': { lat: 13.63, lng: 25.35, country: 'SD', region: 'Africa' },
  tripoli: { lat: 32.90, lng: 13.18, country: 'LY', region: 'North Africa' },
  benghazi: { lat: 32.12, lng: 20.07, country: 'LY', region: 'North Africa' },
  tunis: { lat: 36.82, lng: 10.17, country: 'TN', region: 'North Africa' },
  algiers: { lat: 36.74, lng: 3.06, country: 'DZ', region: 'North Africa' },
  rabat: { lat: 34.02, lng: -6.84, country: 'MA', region: 'North Africa' },
  mogadishu: { lat: 2.05, lng: 45.34, country: 'SO', region: 'Africa' },
  'addis ababa': { lat: 9.03, lng: 38.74, country: 'ET', region: 'Africa' },
  tigray: { lat: 14.05, lng: 38.32, country: 'ET', region: 'Africa' },
  mekele: { lat: 13.50, lng: 39.47, country: 'ET', region: 'Africa' },
  nairobi: { lat: -1.29, lng: 36.82, country: 'KE', region: 'Africa' },
  kampala: { lat: 0.32, lng: 32.58, country: 'UG', region: 'Africa' },
  lagos: { lat: 6.46, lng: 3.38, country: 'NG', region: 'Africa' },
  abuja: { lat: 9.07, lng: 7.40, country: 'NG', region: 'Africa' },
  kinshasa: { lat: -4.32, lng: 15.32, country: 'CD', region: 'Africa' },
  goma: { lat: -1.68, lng: 29.22, country: 'CD', region: 'Africa' },
  bukavu: { lat: -2.51, lng: 28.86, country: 'CD', region: 'Africa' },
  bamako: { lat: 12.65, lng: -8.00, country: 'ML', region: 'Africa' },
  niamey: { lat: 13.51, lng: 2.12, country: 'NE', region: 'Africa' },
  ouagadougou: { lat: 12.37, lng: -1.52, country: 'BF', region: 'Africa' },
  dakar: { lat: 14.72, lng: -17.47, country: 'SN', region: 'Africa' },
  accra: { lat: 5.56, lng: -0.20, country: 'GH', region: 'Africa' },
  luanda: { lat: -8.84, lng: 13.23, country: 'AO', region: 'Africa' },
  harare: { lat: -17.83, lng: 31.05, country: 'ZW', region: 'Africa' },
  johannesburg: { lat: -26.20, lng: 28.04, country: 'ZA', region: 'Africa' },
  pretoria: { lat: -25.75, lng: 28.19, country: 'ZA', region: 'Africa' },
  'cape town': { lat: -33.93, lng: 18.42, country: 'ZA', region: 'Africa' },
  bangui: { lat: 4.36, lng: 18.55, country: 'CF', region: 'Africa' },
  ndjamena: { lat: 12.11, lng: 15.04, country: 'TD', region: 'Africa' },
  juba: { lat: 4.85, lng: 31.60, country: 'SS', region: 'Africa' },
  'south sudan': { lat: 4.85, lng: 31.60, country: 'SS', region: 'Africa' },
  asmara: { lat: 15.34, lng: 38.93, country: 'ER', region: 'Africa' },
  djibouti: { lat: 11.59, lng: 43.15, country: 'DJ', region: 'Africa' },

  // ── Europe ────────────────────────────────────────────────────────────────
  london: { lat: 51.51, lng: -0.13, country: 'GB', region: 'Europe' },
  paris: { lat: 48.86, lng: 2.35, country: 'FR', region: 'Europe' },
  berlin: { lat: 52.52, lng: 13.41, country: 'DE', region: 'Europe' },
  brussels: { lat: 50.85, lng: 4.35, country: 'BE', region: 'Europe' },
  madrid: { lat: 40.42, lng: -3.70, country: 'ES', region: 'Europe' },
  rome: { lat: 41.90, lng: 12.49, country: 'IT', region: 'Europe' },
  warsaw: { lat: 52.23, lng: 21.01, country: 'PL', region: 'Europe' },
  budapest: { lat: 47.50, lng: 19.04, country: 'HU', region: 'Europe' },
  vienna: { lat: 48.21, lng: 16.37, country: 'AT', region: 'Europe' },
  prague: { lat: 50.08, lng: 14.44, country: 'CZ', region: 'Europe' },
  amsterdam: { lat: 52.37, lng: 4.90, country: 'NL', region: 'Europe' },
  stockholm: { lat: 59.33, lng: 18.07, country: 'SE', region: 'Europe' },
  oslo: { lat: 59.91, lng: 10.75, country: 'NO', region: 'Europe' },
  copenhagen: { lat: 55.68, lng: 12.57, country: 'DK', region: 'Europe' },
  helsinki: { lat: 60.17, lng: 24.94, country: 'FI', region: 'Europe' },
  lisbon: { lat: 38.72, lng: -9.14, country: 'PT', region: 'Europe' },
  athens: { lat: 37.98, lng: 23.73, country: 'GR', region: 'Europe' },
  bucharest: { lat: 44.43, lng: 26.10, country: 'RO', region: 'Europe' },
  belgrade: { lat: 44.80, lng: 20.46, country: 'RS', region: 'Europe' },
  zagreb: { lat: 45.81, lng: 15.98, country: 'HR', region: 'Europe' },
  sarajevo: { lat: 43.84, lng: 18.34, country: 'BA', region: 'Europe' },
  pristina: { lat: 42.67, lng: 21.17, country: 'XK', region: 'Europe' },
  minsk: { lat: 53.90, lng: 27.57, country: 'BY', region: 'Europe' },
  chisinau: { lat: 47.01, lng: 28.86, country: 'MD', region: 'Europe' },
  sofia: { lat: 42.70, lng: 23.32, country: 'BG', region: 'Europe' },
  skopje: { lat: 42.00, lng: 21.43, country: 'MK', region: 'Europe' },
  tirana: { lat: 41.33, lng: 19.82, country: 'AL', region: 'Europe' },
  tallinn: { lat: 59.44, lng: 24.75, country: 'EE', region: 'Europe' },
  riga: { lat: 56.95, lng: 24.11, country: 'LV', region: 'Europe' },
  vilnius: { lat: 54.69, lng: 25.28, country: 'LT', region: 'Europe' },

  // ── Caucasus ──────────────────────────────────────────────────────────────
  baku: { lat: 40.41, lng: 49.87, country: 'AZ', region: 'Caucasus' },
  tbilisi: { lat: 41.69, lng: 44.83, country: 'GE', region: 'Caucasus' },
  yerevan: { lat: 40.18, lng: 44.51, country: 'AM', region: 'Caucasus' },
  nagorno: { lat: 39.82, lng: 46.75, country: 'AZ', region: 'Caucasus' },
  karabakh: { lat: 39.82, lng: 46.75, country: 'AZ', region: 'Caucasus' },
  stepanakert: { lat: 39.82, lng: 46.75, country: 'AZ', region: 'Caucasus' },
  grozny: { lat: 43.31, lng: 45.70, country: 'RU', region: 'Caucasus' },
  chechnya: { lat: 43.31, lng: 45.70, country: 'RU', region: 'Caucasus' },

  // ── Central Asia ──────────────────────────────────────────────────────────
  tashkent: { lat: 41.30, lng: 69.27, country: 'UZ', region: 'Central Asia' },
  almaty: { lat: 43.26, lng: 76.95, country: 'KZ', region: 'Central Asia' },
  astana: { lat: 51.18, lng: 71.45, country: 'KZ', region: 'Central Asia' },
  bishkek: { lat: 42.87, lng: 74.59, country: 'KG', region: 'Central Asia' },
  dushanbe: { lat: 38.56, lng: 68.77, country: 'TJ', region: 'Central Asia' },
  ashgabat: { lat: 37.95, lng: 58.38, country: 'TM', region: 'Central Asia' },

  // ── Southeast Asia ─────────────────────────────────────────────────────────
  bangkok: { lat: 13.75, lng: 100.52, country: 'TH', region: 'Southeast Asia' },
  singapore: { lat: 1.35, lng: 103.82, country: 'SG', region: 'Southeast Asia' },
  jakarta: { lat: -6.21, lng: 106.85, country: 'ID', region: 'Southeast Asia' },
  manila: { lat: 14.60, lng: 120.98, country: 'PH', region: 'Southeast Asia' },
  hanoi: { lat: 21.03, lng: 105.85, country: 'VN', region: 'Southeast Asia' },
  'ho chi minh': { lat: 10.82, lng: 106.63, country: 'VN', region: 'Southeast Asia' },
  'kuala lumpur': { lat: 3.14, lng: 101.69, country: 'MY', region: 'Southeast Asia' },
  yangon: { lat: 16.87, lng: 96.19, country: 'MM', region: 'Southeast Asia' },
  rangoon: { lat: 16.87, lng: 96.19, country: 'MM', region: 'Southeast Asia' },
  myanmar: { lat: 19.75, lng: 96.08, country: 'MM', region: 'Southeast Asia' },
  naypyidaw: { lat: 19.75, lng: 96.08, country: 'MM', region: 'Southeast Asia' },
  mandalay: { lat: 21.97, lng: 96.08, country: 'MM', region: 'Southeast Asia' },
  phnom: { lat: 11.56, lng: 104.93, country: 'KH', region: 'Southeast Asia' },
  'phnom penh': { lat: 11.56, lng: 104.93, country: 'KH', region: 'Southeast Asia' },
  vientiane: { lat: 17.97, lng: 102.60, country: 'LA', region: 'Southeast Asia' },
  'bandar seri begawan': { lat: 4.94, lng: 114.95, country: 'BN', region: 'Southeast Asia' },
  dili: { lat: -8.56, lng: 125.58, country: 'TL', region: 'Southeast Asia' },

  // ── East Asia ──────────────────────────────────────────────────────────────
  tokyo: { lat: 35.69, lng: 139.69, country: 'JP', region: 'East Asia' },
  seoul: { lat: 37.57, lng: 126.98, country: 'KR', region: 'East Asia' },
  pyongyang: { lat: 39.02, lng: 125.75, country: 'KP', region: 'East Asia' },
  ulaanbaatar: { lat: 47.89, lng: 106.91, country: 'MN', region: 'East Asia' },

  // ── South Asia ─────────────────────────────────────────────────────────────
  dhaka: { lat: 23.72, lng: 90.41, country: 'BD', region: 'South Asia' },
  kathmandu: { lat: 27.71, lng: 85.31, country: 'NP', region: 'South Asia' },
  colombo: { lat: 6.93, lng: 79.84, country: 'LK', region: 'South Asia' },

  // ── Americas ────────────────────────────────────────────────────────────────
  washington: { lat: 38.91, lng: -77.04, country: 'US', region: 'North America' },
  'new york': { lat: 40.71, lng: -74.01, country: 'US', region: 'North America' },
  toronto: { lat: 43.65, lng: -79.38, country: 'CA', region: 'North America' },
  'mexico city': { lat: 19.43, lng: -99.13, country: 'MX', region: 'Latin America' },
  mexico: { lat: 19.43, lng: -99.13, country: 'MX', region: 'Latin America' },
  havana: { lat: 23.14, lng: -82.36, country: 'CU', region: 'Latin America' },
  caracas: { lat: 10.49, lng: -66.88, country: 'VE', region: 'Latin America' },
  bogota: { lat: 4.71, lng: -74.07, country: 'CO', region: 'Latin America' },
  brasilia: { lat: -15.78, lng: -47.93, country: 'BR', region: 'Latin America' },
  'sao paulo': { lat: -23.55, lng: -46.63, country: 'BR', region: 'Latin America' },
  'rio de janeiro': { lat: -22.91, lng: -43.17, country: 'BR', region: 'Latin America' },
  'buenos aires': { lat: -34.61, lng: -58.38, country: 'AR', region: 'Latin America' },
  santiago: { lat: -33.46, lng: -70.65, country: 'CL', region: 'Latin America' },
  lima: { lat: -12.05, lng: -77.04, country: 'PE', region: 'Latin America' },
  quito: { lat: -0.23, lng: -78.52, country: 'EC', region: 'Latin America' },
  'port-au-prince': { lat: 18.54, lng: -72.34, country: 'HT', region: 'Latin America' },
  managua: { lat: 12.13, lng: -86.28, country: 'NI', region: 'Latin America' },
  tegucigalpa: { lat: 14.07, lng: -87.21, country: 'HN', region: 'Latin America' },
  'san salvador': { lat: 13.70, lng: -89.20, country: 'SV', region: 'Latin America' },
  'guatemala city': { lat: 14.64, lng: -90.51, country: 'GT', region: 'Latin America' },

  // ── Oceania ────────────────────────────────────────────────────────────────
  sydney: { lat: -33.87, lng: 151.21, country: 'AU', region: 'Pacific' },
  canberra: { lat: -35.28, lng: 149.13, country: 'AU', region: 'Pacific' },
  'port moresby': { lat: -9.44, lng: 147.18, country: 'PG', region: 'Pacific' },
  suva: { lat: -18.14, lng: 178.44, country: 'FJ', region: 'Pacific' },
  noumea: { lat: -22.28, lng: 166.47, country: 'NC', region: 'Pacific' },
}
